[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
  'cp package-server.json package.json',
  'npm install --production --no-optional'
]

[phases.build]
cmds = ['echo "No build step needed"']

[start]
cmd = 'node server/server.js'
